name: API Estoque test
on: 
    pull_request:
        branches: 
            - main

jobs:
    test:
        runs-on: windows-latest
        defaults: 
            run:
                working-directory: ./src/
        
        
        steps:
            - uses: actions/checkout@v3

            - name: Set up Spring
              uses: actions/setup-java@v3
              with:
                  java-version: '17'

            - name: Set up Java
              run: mvn -B package --file pom.xml

